title: Marcel Peter Kong
logo: /images/pic1.png
description: >
  **Skills**:<br>
  - Python<br>
  - SQL<br>
  - Tableau / Power BI<br>
  - Advanced excel / VBA<br>
  - Data Analysis<br>
  - Statistics<br>
  <br>
  Contact:<br>
  ðŸ“ž +63-995-032-3545<br>
  ðŸ“§ konggiio2@gmail.com
theme: jekyll-theme-minimal
github: 
  is_project_page: false
