title: Marcel Peter Kong
logo: /images/pic1.png
description: >
  <span style="color: rgb(0, 119, 181);font-size: 22px; font-weight: bold;">ðŸ’¡Skills</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾Python</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾SQL</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾Tableau / Power BI</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾Advanced Excel / VBA</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾Data Analysis</span><br>
   <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">â—¾Statistics</span><br>
  <br>
  <span style="color: rgb(0, 119, 181);font-size: 22px; font-weight: bold;">ðŸ“’Contact Information</span><br>
    <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">ðŸ“ž +63-995-032-3545</span><br>
    <span style="color: rgb(0, 119, 181);font-size: 20px;padding-left: 20px;">ðŸ“§ konggiio2@gmail.com</span>
theme: jekyll-theme-minimal
github: 
  is_project_page: false
