title: Marcel Peter Kong
logo: /images/pic1.png
description: >
  **Skills**: ğŸ› ï¸ ğŸ’ª ğŸ§ <br>
  - Python<br>
  - SQL<br>
  - Tableau<br>
  - Advanced excel / VBA<br>
  - Data Analysis<br>
  - Statistics
theme: jekyll-theme-minimal
github: 
  is_project_page: false
