title: Marcel Peter Kong
logo: /images/pic1.png
description: >
  **Skills**: ğŸ› ï¸ ğŸ’ª ğŸ§ 
  - Python
  - SQL
  - Tableau
  - Advanced excel / VBA
  - Data Analysis
  - Statistics
theme: jekyll-theme-minimal
github: 
  is_project_page: false
