title: Marcel Peter Kong
logo: /images/pic1.png
description: >
  **Skills**: ğŸ› ï¸ ğŸ’ª ğŸ§ <br>
  - Python<br>
  - SQL<br>
  - Tableau / Power BI<br>
  - Advanced excel / VBA<br>
  - Data Analysis<br>
  - Statistics<br>
  <br>
  <br>
  Contact:<br>
  - :telephone_receiver: +63-995-032-3545<br>
  - :email: konggiio2@gmail.com
theme: jekyll-theme-minimal
github: 
  is_project_page: false
